### ISSUE TITLE
Programador PHP Pleno e Sênior - SP

### ISSUE THREAD

**Issue by RADARProfissional** [brasil-php/vagas#1]
## Descrição da vaga
Programador PHP Pleno e Sênior - SP

•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência HTML, CSS, JS; REST e Integração de API´s, Webservices, CSS, SASS, LESS, versionamento GIT, Framework Angular I/II, React, Vue.JS, automatizador de tarefas, SEO.

## Local
São Paulo - SP

## Benefícios
AM, AO, SV, VR, VT e outros.

## Requisitos
•	Superior completo em Administração, Análise de Sistemas, Ciências da Computação, Tecnologia da Informação, Engenharia da Computação ou áreas afins;
•	Experiência HTML, CSS, JS; REST e Integração de API´s, Webservices, CSS, SASS, LESS, versionamento GIT, Framework Angular I/II, React, Vue.JS, automatizador de tarefas, SEO.

## Contratação

CLT

## Nossa empresa
RADAR Profissional - Consultoria de Recrutamento & Seleção e Terceirização de Profissionais

## Como se candidatar
Interessados enviar CV com a pretensão salarial para analista@radaprofissional.com.br ou recrutadora@radarprofissional.com.br com sua pretensão salarial

**Comment by RafaelaCassianoCampos** [comment]
a vaga já foi preenchida?

**Comment by RADARProfissional** [comment]
Sim, Já foi preenchida!

 

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: RafaelaCassianoCampos [mailto:notifications@github.com] 
Enviada em: quarta-feira, 11 de outubro de 2017 18:45
Para: brasil-php/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [brasil-php/vagas] Programador PHP Pleno e Sênior - SP (#1)

 

a vaga já foi preenchida?
