### ISSUE TITLE
[CENTO/SP] Desenvolvedor(a) PHP Pleno - IT Singular

### ISSUE THREAD

**Issue by andvictor** [brasil-php/vagas#17]
Programador PHP nível Pleno
Local: Centro de SP
Contratação PJ por tempo indeterminado
Faixa salarial de 8.6k

Precisamos que você saiba de:
- PHP
- Programação de testes unitários e automatização de testes integrados
- Produção de código limpo, documentado e bem organizado
- Redis
- Elastic Search e MongoDB
- Aceleração de performance e caching
- Linux
- Programação LAMP (Linux, Apache, PHP e MySQL).
- Framework Laravel (ou outro)

Me se interessou mande um e-mail: avieira@itsingular.com

**Comment by paulop** [comment]
Bom dia, 
Uma dúvida.
Qual seria o setor PJ para essa categoria?
Acredito que MEI não sei encaixa.

**Comment by andvictor** [comment]
> Bom dia,
> Uma dúvida.
> Qual seria o setor PJ para essa categoria?
> Acredito que MEI não sei encaixa.

Se encaixa sim, não temos uma limitação para o tio de empresa.
